### ISSUE TITLE
hdevtools does not build with Cabal 2.0.1.1

### ISSUE THREAD

**Issue by mwuttke97** [hdevtools/hdevtools#75]
**System:**
> OS: Arch Linux
> ghc: The Glorious Glasgow Haskell Compilation System, version 8.0.2

**Version of hdevtools:**
> git master

**Version of Cabal:**
> Cabal 2.0.1.1 and 1.24.2.0 are installed.

**Version of cabal-install:**
> version 2.0.0.1 compiled using version 2.0.1.1 

**Command to build hdevtools:**
> cabal build

**Output:**

```
Resolving dependencies...
Configuring hdevtools-0.1.6.0...
Preprocessing executable 'hdevtools' for hdevtools-0.1.6.0..
Building executable 'hdevtools' for hdevtools-0.1.6.0..
[ 3 of 13] Compiling Stack            ( src/Stack.hs, dist/build/hdevtools/hdevtools-tmp/Stack.o ) [dist/build/hdevtools/autogen/cabal_macros.h changed]
[ 4 of 13] Compiling Info             ( src/Info.hs, dist/build/hdevtools/hdevtools-tmp/Info.o ) [dist/build/hdevtools/autogen/cabal_macros.h changed]
[ 5 of 13] Compiling FindSymbol       ( src/FindSymbol.hs, dist/build/hdevtools/hdevtools-tmp/FindSymbol.o ) [dist/build/hdevtools/autogen/cabal_macros.h changed]
[ 7 of 13] Compiling Cabal            ( src/Cabal.hs, dist/build/hdevtools/hdevtools-tmp/Cabal.o ) [Distribution.Version changed]

src/Cabal.hs:140:59: error:
    • Couldn't match type ‘(t0, PackageIdentifier, t1)’
                     with ‘(Distribution.Backpack.OpenUnitId,
                            Distribution.Types.ModuleRenaming.ModuleRenaming)’
      Expected type: NubListR
                       (Distribution.Backpack.OpenUnitId,
                        Distribution.Types.ModuleRenaming.ModuleRenaming)
        Actual type: NubListR (t0, PackageIdentifier, t1)
    • In the ‘ghcOptPackages’ field of a record
      In the expression:
        ghcOpts'
          {ghcOptExtra = overNubListR (filter (/= "-Werror"))
                         $ ghcOptExtra ghcOpts',
           ghcOptPackageDBs = sort $ nub (ghcOptPackageDBs ghcOpts'),
           ghcOptPackages = overNubListR
                              (filter (\ (_, pkgId, _) -> Just (pkgName pkgId) /= mbLibName))
                            $ (ghcOptPackages ghcOpts'),
           ghcOptSourcePath = overNubListR
                                (map (baseDir </>)) (ghcOptSourcePath ghcOpts')}
      In an equation for ‘ghcOpts’:
          ghcOpts
            = ghcOpts'
                {ghcOptExtra = overNubListR (filter (/= "-Werror"))
                               $ ghcOptExtra ghcOpts',
                 ghcOptPackageDBs = sort $ nub (ghcOptPackageDBs ghcOpts'),
                 ghcOptPackages = overNubListR
                                    (filter (\ (_, pkgId, _) -> Just (pkgName pkgId) /= mbLibName))
                                  $ (ghcOptPackages ghcOpts'),
                 ghcOptSourcePath = overNubListR
                                      (map (baseDir </>)) (ghcOptSourcePath ghcOpts')}

src/Cabal.hs:140:138: error:
    • Couldn't match type ‘(Distribution.Backpack.OpenUnitId,
                            Distribution.Types.ModuleRenaming.ModuleRenaming)’
                     with ‘(t0, PackageIdentifier, t1)’
      Expected type: NubListR (t0, PackageIdentifier, t1)
        Actual type: NubListR
                       (Distribution.Backpack.OpenUnitId,
                        Distribution.Types.ModuleRenaming.ModuleRenaming)
    • In the second argument of ‘($)’, namely
        ‘(ghcOptPackages ghcOpts')’
      In the ‘ghcOptPackages’ field of a record
      In the expression:
        ghcOpts'
          {ghcOptExtra = overNubListR (filter (/= "-Werror"))
                         $ ghcOptExtra ghcOpts',
           ghcOptPackageDBs = sort $ nub (ghcOptPackageDBs ghcOpts'),
           ghcOptPackages = overNubListR
                              (filter (\ (_, pkgId, _) -> Just (pkgName pkgId) /= mbLibName))
                            $ (ghcOptPackages ghcOpts'),
           ghcOptSourcePath = overNubListR
                                (map (baseDir </>)) (ghcOptSourcePath ghcOpts')}
[11 of 13] Compiling Paths_hdevtools  ( dist/build/hdevtools/autogen/Paths_hdevtools.hs, dist/build/hdevtools/hdevtools-tmp/Paths_hdevtools.o )
```

**Possible Reason for the error:**
hdevtools is incompatible with Cabal 2.*, because of changed types, etc. `cabal build` will use newest version of the cabal library, because of the greater-or-equal constraints in `hdevtools.cabal`.

**Working Work-Around:**
Compile using Cabal 1.24.2.0, by adding `  build-depends:       Cabal == 1.24.2.0` to `hdevtools.cabal`

**Proposed Fix:**
Either make it compatible with Cabal 2.*,  or add a less-or-equal version constraint to `hdevtools.cabal`, e.g.
`  build-depends:       Cabal < 2`

**Comment by ch1bo** [comment]
Just successfully compiled it with `ghc-8.2.2` against `Cabal-2.0.1.1`. Thus it should be solved in `hdevtools-0.1.6.1`, can you comment if still relevant?

**Comment by mwuttke97** [comment]
I just git checked out to `hdevtools-0.1.6.1` and did the same steps as above, i.e. `cabal clean && cabal build`.
I got the same typing error, on the same line, i.e. https://github.com/hdevtools/hdevtools/blob/master/src/Cabal.hs#L140

Do you need more debugging information?

**Comment by benzrf** [comment]
I can corroborate this issue on GHC 8.4.2 with hdevtools 0.1.6.1.

**Comment by ch1bo** [comment]
@mwuttke97 Are you sure that you `cabal` is using ghc-8.0.2? As you correctly say, the CPP section should not be included for compilation and hdevtools-0.1.6.1 is indeed working with ghc-8.0.2 - as it is built and used in stackage `lts-9.21`

@benzrf So you have another error, but with ghc-8.4.2? Is it already covered by an issue or do you want to create one with your error?

**Comment by mwuttke97** [comment]
@ch1bo I double-checked the version outputs and they were the same as above.
However, I didn't do any more tests, since I don't code haskell at the moment. :-(

I think that this issue is specific to the versions of ghc&cabal as copy-pasted above. This may need more testing. Unfortunately, I don't have the exact ghc version (8.0.2) installed any more.

**Comment by ch1bo** [comment]
Should be also solved with #91

**Comment by ch1bo** [comment]
New release 0.1.8.0 should be tried here. Will close until reported again
