### ISSUE TITLE
hdevtools fails to build with network-3.0.0.0

### ISSUE THREAD

**Issue by jrahm** [hdevtools/hdevtools#90]
It appears that a recent update in the network package to version 3.0.0.0 has broken hdevtools. In this change the `Network` package was removed. (see http://hackage.haskell.org/package/network-3.0.1.0/changelog)

```
  src/Server.hs:7:1: error:
      Failed to load interface for ‘Network’
      Use -v to see a list of the files searched for.
  cabal: Leaving directory '/tmp/cabal-tmp-80945/hdevtools-0.1.7.0'
  cabal: Error: some packages failed to install:
  hdevtools-0.1.7.0 failed during the building phase. The exception was:
```

This problem can be mitigated by explicitly adding network <3.0.0.0 in the hdevtool.cabal file and building in a cabal sandbox.
